---
title: "excel_file_uploads"
author: "Candi Pierce"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r echo=FALSE, warning=FALSE, message=FALSE}
library(utHelpR)
library(janitor)
library(here)
library(tidyverse)
library(readxl)
library(lubridate)
library(tidyr)
library(dplyr)
```



```{r, warning=FALSE, message=FALSE}
deferred_df <- read_csv("/Volumes/Share/Research/National Student Clearing House/DE_LOA_requests/LOA Clearinghouse check spring 26 list.csv") %>% 
  rename(student_id = Student_ID, last_name = Last_Name, first_name = First_Name, birth_date = BirthDate) %>% 
  mutate(birth_date = format(as.Date(birth_date, format = "%m/%d/%y"), "%Y-%m-%d")) %>% 
  mutate(term_id = '202440') %>% 
  mutate(term_end_date = as.Date("2024-05-05")) 
```

```{r}
nsc_from_edify_enrolled <- utHelpR::get_data_from_sql_file('de_loa_details.sql','edify','project')
```

```{r}
loa_de_df <- deferred_df %>% 
  left_join(nsc_from_edify_enrolled, join_by(student_id))
```




## Declare Variables for NSC Submission File
### Variables
```{r}
school_code <- '003671'
branch_code <- '00'
school_name <- 'Utah Tech University'
query_option <- 'SE'
```

### Record Type and Variables for NSC Header
### Header for submission file
```{r}
header <- tibble(header = 'H1',
                 school_code = school_code,
                 branch_code = branch_code,
                 school_name = str_pad(school_name, width = 20, side = "right"),
                 file_creation_date = str_remove_all(today(), "-"),
                 query_option = query_option,
                 institution = 'I'
                 )
```




## Create Enrolled file for upload
```{r}
enrolled_file <- loa_de_df %>% 
  mutate(
    detail_records = 'D1',
    ssn = str_pad(' ',9),
    first_name = str_sub(str_pad(str_remove_all(first_name, "[-,.*()`']"), 20, side = 'right'), 1, 20),
    middle_initial = replace_na(substr(str_remove_all(middle_initial, "."), 1, 1), ''),
    last_name =  str_sub(str_pad(replace_na(str_remove_all(last_name, "[-,.*()`']"), NA), 20, side = 'right'), 1, 20),
    suffix = str_pad(replace_na(str_remove_all(name_suffix,"[-,.']"), ''), 5, side = 'right'), 
    birth_date = str_pad(replace_na(str_remove_all(birth_date, "-"),NA), 18 , side = 'left'),
    term_end_date = str_remove_all(term_end_date, "-"),
    blank_column = '',
    school_code = school_code,
    branch_code = branch_code,
    requester_return_field = student_id,
    unique_id = duplicated(requester_return_field)
  ) %>%
   select (detail_records, ssn, first_name, middle_initial, last_name, suffix, birth_date, term_end_date, blank_column, school_code, branch_code, requester_return_field)
```




### Record Type and Count for NSC Trailer
### Trailer for enrolled submission file
```{r}
trailer <- tibble(trailer = 'T1',
                  records = nrow(enrolled_file) + 2
                  )
```

## Generate NSC File
```{r}
file_name <- "de_loa_nsc_upload.tsv"
file_path <- here::here('/Volumes/Share/Research/National Student Clearing House/DE_LOA_requests/')

write_tsv(header, paste0(file_path, file_name), col_names = FALSE, na = '')
write_tsv(enrolled_file, paste0(file_path, file_name), append = TRUE, na = '')
write_tsv(trailer, paste0(file_path, file_name), append = TRUE, na = '')
```

