--pull in data from the national student clearinghouse
SELECT  sys_student_id AS your_unique_identifier,
        first_name,
        middle_initial,
        last_name,
        name_suffix,
        requester_return_field,
        record_found_y_n,
        search_date,
        college_code_branch,
        college_name,
        college_state,
        two_year_four_year,
        public_private,
        enrollment_begin,
        enrollment_end,
        enrollment_status,
        class_level,
        enrollment_major_1,
        enrollment_cip_1,
        enrollment_major_2,
        enrollment_cip_2,
        graduated,
        graduation_date,
        degree_title,
        degree_major_1,
        degree_cip_1,
        degree_major_2,
        degree_cip_2,
        degree_major_3,
        degree_cip_3,
        degree_major_4,
        degree_cip_4,
        college_sequence,
        nsc_key
FROM quad.nsc_outcomes;
